### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by runishiwo** [Xtao-Labs/PagerMaid-Modify#167]
### BUG 发生地址
平台检测为“linux，进入PagerMaid的早期加载过程等了一会儿,报错
### 预期是什么？
搭建完成
### 实际发生了什么？
搭建失败
### 额外信息（日志、报错等）

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/pagermaid/workdir/pagermaid/__init__.py", line 268, in <module>
    with bot:
  File "/usr/local/lib/python3.8/dist-packages/telethon/helpers.py", line 184, in _sync_enter
    return loop.run_until_complete(self.__aenter__())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/auth.py", line 713, in __aenter__
    return await self.start()
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/auth.py", line 140, in _start
    await self.connect()
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/telegrambaseclient.py", line 525, in connect
    if not await self._sender.connect(self._connection(
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 127, in connect
    await self._connect()
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 253, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)

**Comment by newkld** [comment]
@runishiwo 机子连不上TG服务器
