### ISSUE TITLE
安装keyword插件后无限报错

### ISSUE THREAD

**Issue by imzrme** [Xtao-Labs/PagerMaid-Modify#43]
### 额外信息（日志、报错等）
# Generated: 04:20 20/01/2021. 
# ChatID: -1001441461877. 
# UserID: 1263764543. 
# Message: 
-----BEGIN TARGET MESSAGE-----
#ERROR #id626524659 
鏀跺埌鏉ヨ嚜鐢ㄦ埛锛歔MZRME](tg://user?id=626524659) 鐨勪竴椤规姤閿欍€�
-----END TARGET MESSAGE-----
# Traceback: 
-----BEGIN TRACEBACK-----
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/pagermaid/pagermaid/listener.py", line 64, in handler
    await function(context)
  File "/var/lib/pagermaid/plugins/keyword.py", line 347, in auto_reply
    plain_dict = get_redis(f"keyword.{chat_id}.plain")
  File "/var/lib/pagermaid/plugins/keyword.py", line 56, in get_redis
    byte_data = redis.get(db_key)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

-----END TRACEBACK-----
# Error: "Error 111 connecting to localhost:6379. Connection refused.".

**Comment by Pentacene** [comment]
Please send issue [here](https://github.com/Xtao-Labs/PagerMaid_Plugins/issues/new).

This issue belongs to PagerMaid-Plugins. I will close this issue.

You may at that author in your new issue.
