### ISSUE TITLE
-update true执行失败

### ISSUE THREAD

**Issue by onoc1yn** [Xtao-Labs/PagerMaid-Modify#47]
### BUG 发生地址
-update true
### 预期是什么？
执行更新
### 实际发生了什么？
更新失败
### 额外信息（日志、报错等）
# Generated: 08:11 01/02/2021.
# ChatID: ***
# UserID: ***
# Message:
-----BEGIN TARGET MESSAGE-----
-update true
-----END TARGET MESSAGE-----
# Traceback:
-----BEGIN TRACEBACK-----
Traceback (most recent call last):
  File "/var/lib/pagermaid/pagermaid/listener.py", line 64, in handler
    await function(context)
  File "/var/lib/pagermaid/pagermaid/modules/update.py", line 69, in update
    changelog = await changelog_gen(repo, f'HEAD..upstream/{active_branch}')
  File "/var/lib/pagermaid/pagermaid/modules/update.py", line 122, in changelog_gen
    for c in repo.iter_commits(diff):
  File "/usr/local/lib/python3.6/site-packages/git/objects/commit.py", line 277, in _iter_from_process_or_stream
    finalize_process(proc_or_stream)
  File "/usr/local/lib/python3.6/site-packages/git/util.py", line 329, in finalize_process
    proc.wait(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-list HEAD..upstream/master --
  stderr: 'fatal: bad revision 'HEAD..upstream/master'
'

-----END TRACEBACK-----
# Error: "Cmd('git') failed due to: exit code(128)
  cmdline: git rev-list HEAD..upstream/master --
  stderr: 'fatal: bad revision 'HEAD..upstream/master'
'".

**Comment by NonCheng** [comment]
@onoc1yn 安装git了吗
或者更新一下git？

**Comment by OwO996** [comment]
-sh git pull 试试嘞。

**Comment by onoc1yn** [comment]
> @onoc1yn 安装git了吗
> 或者更新一下git？

当然装了的，git pull 正常。

**Comment by xtaodada** [comment]
git 版本过低 centos ，请自行编译安装最新 git

**Comment by KLDGodY** [comment]
@xtaodada 所以 建议把一键脚本给改了
